{% set name = "pymt_gipl" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 78915516556eb87ba814c0a9de9cc9f7779dc3f603e4fbc2a14760eb2d19586a

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - bmi-fortran =1.2.1                     # [build_platform != target_platform]
    - gipl                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - meson-python
    - ninja
    - pkg-config
    - python-build
    - model_metadata
    - bmi-fortran =1.2.1
    - gipl
  run:
    - python
    - bmi-fortran =1.2.1
    - gipl

test:
  imports:
    - pymt_gipl

about:
  home: https://github.com/pymt-lab/pymt_gipl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the GIPL model.
  dev_url: https://github.com/pymt-lab/pymt_gipl

extra:
  recipe-maintainers:
    - mdpiper
