travis:
  secure:
    BINSTAR_TOKEN: DBtQ0DCstk8bZHe65YG5JbuPQySBG0y7245rIGMJBcaoM+OnmG8Pp95Lh6Z+/1N9ekT3x/vIzG5ZWyrnO4f/39GJVGeVEw0KvviriWrtmg0e7/EIl6s+u7Jm1Bqbiw9YlhyNFKbUEp6tzXW88oeGpombyjZGSgVm4edechz74vt9+YrAlqHxnmT5S9UHZbzela5Gb0fJOZ8Co6/ysch5vt5EziJ/U+dVRcb/TmPywXT3ys9+omEZgPs3R2yiUHFGx8UtxAbgeu2eFlWzZVP3V/w8pHLH1O4WX08Zh913l/Jt2oWco1elty5OUWu008IkSVBuC9BtY5DeDQtBMhuanzfV6PXTWSe7eyOTTRcpILCv3SQz2Ni5FUe2qoxS1cODsRkXQAKAeNXKA4OP/KLZ68Ne/6j/UsQaH+dbLo1V6lnYg54W29sT+xdGoyxgeQ9xdxr5y8roBQfSLlhPtGKIyk9i+F0knJ1F/5EhRoLEPvWgitUXKyPS2qcUWwDvpNDmFgweCpn5vh3sK9Oqk7XZ8VWP2Z1Yxt12lKL826ouwRCZIgajgza8OHuT1QvdAsPa1v74PFIrFYXtOHY5BRz/a2/Y32eLIb8muXQaxDuIeAcmC6jhhz9Ci28A2ddHRThk/rlVIfifYfCz48v0j37SKBUQWGbI6tmku8U3SvSyfOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
